"""
ReportFlow Branding & Template Customisation Module.

Allows users to configure company identity (logo, colours, fonts, footer text)
and to supply a fully custom Jinja2 HTML template without touching the core
pipeline code.

Usage
-----
Via config.json::

    {
        "title": "Q3 Financial Report",
        "branding": {
            "company_name": "Acme Corp",
            "logo_url": "https://example.com/logo.png",
            "primary_color": "#0f4c81",
            "accent_color": "#f59e0b",
            "font_family": "Inter, sans-serif",
            "footer_text": "Confidential — Acme Corp Finance Team",
            "custom_template_path": null
        },
        "sources": [...]
    }

Via Python API::

    from reportflow.branding import BrandingConfig, apply_branding
    brand = BrandingConfig(company_name="Acme Corp", primary_color="#0f4c81")
    html = apply_branding(template_str, context, brand)
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, BaseLoader, TemplateNotFound
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Branding configuration model
# ---------------------------------------------------------------------------

class BrandingConfig(BaseModel):
    """
    All visual / identity settings for a generated report.

    All fields are optional — sensible defaults produce a clean, professional
    look without any configuration.
    """

    company_name: str = Field("ReportFlow", description="Company or team name shown in the header")
    tagline: str = Field("Automated Financial Intelligence", description="Subtitle shown below the title")
    logo_url: Optional[str] = Field(None, description="Absolute URL or data-URI for the company logo")
    logo_alt: str = Field("Company Logo", description="Alt text for the logo image")

    # Colours (CSS hex values)
    primary_color: str = Field("#1e3a8a", description="Primary brand colour (header gradient start)")
    secondary_color: str = Field("#3b82f6", description="Secondary brand colour (header gradient end)")
    accent_color: str = Field("#f59e0b", description="Accent colour used for badges and highlights")
    text_color: str = Field("#1f2937", description="Main body text colour")
    background_color: str = Field("#f8f9fa", description="Page background colour")
    card_border_color: str = Field("#e5e7eb", description="Card border colour")

    # Typography
    font_family: str = Field(
        "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        description="CSS font-family stack",
    )
    heading_font_family: Optional[str] = Field(
        None, description="Override font for headings (falls back to font_family)"
    )

    # Footer
    footer_text: str = Field(
        "Generated by ReportFlow Automation",
        description="Text shown in the report footer",
    )
    show_sha256: bool = Field(True, description="Whether to display SHA-256 hashes in provenance section")
    show_powered_by: bool = Field(True, description="Whether to show 'Powered by ReportFlow' badge")

    # Custom template
    custom_template_path: Optional[str] = Field(
        None,
        description=(
            "Path to a custom Jinja2 HTML template file.  "
            "If provided, the built-in template is ignored.  "
            "The template receives the same context variables as the default template."
        ),
    )

    model_config = {"extra": "allow"}  # forward-compat: unknown keys are silently ignored


# ---------------------------------------------------------------------------
# Template context helpers
# ---------------------------------------------------------------------------

BUILTIN_TEMPLATE_DIR = Path(__file__).parent / "templates"
BUILTIN_TEMPLATE_NAME = "report.html"


def _build_css_vars(brand: BrandingConfig) -> str:
    """Return a CSS :root block with all brand tokens as custom properties."""
    heading_ff = brand.heading_font_family or brand.font_family
    return f"""
    :root {{
        --rf-primary:     {brand.primary_color};
        --rf-secondary:   {brand.secondary_color};
        --rf-accent:      {brand.accent_color};
        --rf-text:        {brand.text_color};
        --rf-bg:          {brand.background_color};
        --rf-card-border: {brand.card_border_color};
        --rf-font:        {brand.font_family};
        --rf-heading-font:{heading_ff};
    }}
    """.strip()


def build_template_context(
    base_context: dict,
    brand: BrandingConfig,
) -> dict:
    """
    Merge pipeline context with branding variables so templates can use
    ``{{ brand.company_name }}``, ``{{ css_vars | safe }}``, etc.
    """
    ctx = dict(base_context)
    ctx["brand"] = brand
    ctx["css_vars"] = _build_css_vars(brand)
    return ctx


# ---------------------------------------------------------------------------
# Jinja2 environment factory
# ---------------------------------------------------------------------------

def _make_env_for_custom(template_path: Path) -> tuple[Environment, str]:
    """Return (env, template_name) for a user-supplied template file."""
    env = Environment(loader=FileSystemLoader(str(template_path.parent)))
    return env, template_path.name


def _make_env_builtin() -> tuple[Environment, str]:
    """Return (env, template_name) for the built-in template."""
    env = Environment(loader=FileSystemLoader(str(BUILTIN_TEMPLATE_DIR)))
    return env, BUILTIN_TEMPLATE_NAME


def get_jinja_env(brand: BrandingConfig) -> tuple[Environment, str]:
    """
    Return the correct (Jinja2 Environment, template_name) pair based on
    whether a custom template path is configured.
    """
    if brand.custom_template_path:
        p = Path(brand.custom_template_path)
        if not p.exists():
            raise FileNotFoundError(
                f"custom_template_path not found: {p.resolve()}"
            )
        logger.info("Using custom template: %s", p.resolve())
        return _make_env_for_custom(p)

    logger.debug("Using built-in template: %s", BUILTIN_TEMPLATE_NAME)
    return _make_env_builtin()
